apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-app
  labels: 
    app: api-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-app
  template:
    metadata:
      labels:
        app: api-app
    spec:
      containers:
      - name: api-app
        image: shariquetech1987/devops-qrcode-api:0.0.1
        ports:
        - name: api-app-port
          containerPort: 8000
