apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app
  labels: 
    app: frontend-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-app
  template:
    metadata:
      labels:
        app: frontend-app
    spec:
      containers:
      - name: frontend-app
        image: shariquetech1987/devops-qrcode-front-end:0.0.1
        ports:
        - name: frontend-app-port
          containerPort: 3000
