# This workflow will build docker images and deploy to EKS

name: NextJs and FastApi App deploy to EKS

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'infra/**'
  
  workflow_dispatch:

env:
  EKS_CLUSTER_NAME: demo-cluster
  AWS_REGION: us-east-1

jobs:
  deploy:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Install kubectl
      uses: azure/setup-kubectl@v4
      with:
        version: 'latest' # default is latest stable
      id: install

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Build and Push API Docker Image
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
        image: shariquetech1987/devops-qrcode-api
        registry: docker.io
        dockerfile: ./api/Dockerfile
        tag: latest
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Front-End Docker Image
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
        image: shariquetech1987/devops-qrcode-front-end
        registry: docker.io
        dockerfile: ./front-end-nextjs/Dockerfile
        tag: latest
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Update kube config
      run: aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region $AWS_REGION
      
    - name: Deploy to EKS
      run: |
          cd kubernetes/
          ls -l
          kubectl apply -f api-dep.yaml
          kubectl apply -f api-service.yaml
          kubectl apply -f front-end-dep.yaml
          kubectl apply -f front-end-service.yaml
          kubectl apply -f ingress.yaml
         
