# This workflow will build docker images and deploy to EKS

name: NextJs and FastApi App deploy to EKS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Build and Push API Docker Image
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
        image: shariquetech1987/devops-qrcode-api
        registry: docker.io
        dockerfile: ./api/Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
         